#!/usr/bin/env python3
"""Generate src/moy_data.c from the spec's normative data files.

    python3 tools/embed_data.py

palette.json and font.bin are NORMATIVE -- SPEC.md 2 says the colour table is
"data, not prose" precisely so conformance has exact values to check, and
SPEC.md 6 says the font "must be byte-identical across implementations or all
text conformance fails". They live one directory up.

So they are generated here, never hand-typed. A C array of 192 numbers someone
transcribed is a fork of the palette waiting to happen: it would look right,
compile, run, and disagree with every other implementation on colour 37. The
generated file records which spec commit it came from, so a drift is a diff.
"""

import argparse
import hashlib
import json
import os
import sys


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default=os.path.join(
                        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".."),
                    help="the spec root (default: the parent of libmoy/)")
    ap.add_argument("--out", default=None)
    a = ap.parse_args(argv)

    pal_path = os.path.join(a.spec, "palette.json")
    font_path = os.path.join(a.spec, "font.bin")
    with open(pal_path, encoding="utf-8") as f:
        palette = json.load(f)
    with open(font_path, "rb") as f:
        font = f.read()

    if len(palette) != 64:
        sys.exit("palette.json has %d entries, expected 64" % len(palette))
    if len(font) != 96 * 8:
        sys.exit("font.bin is %d bytes, expected %d" % (len(font), 96 * 8))

    rgb = []
    for entry in palette:
        s = entry.lstrip("#")
        rgb.extend((int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)))

    out = a.out or os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "src", "moy_data.c")

    lines = [
        "/* GENERATED by tools/embed_data.py -- do not edit.",
        " *",
        " * The spec's normative data, compiled in: palette.json (SPEC.md 2) and",
        " * font.bin (SPEC.md 6). Both are data rather than prose precisely so that",
        " * implementations cannot drift on them, so neither is hand-written here.",
        " *",
        " * Regenerate with:  make data",
        " *",
        " * The hashes are the drift check: regenerating must be a no-op, and CI",
        " * asserts it. Deliberately NO commit id -- this file is versioned beside",
        " * the data it comes from, so git already knows, and stamping HEAD here",
        " * would change the file on every commit and make that check unsatisfiable.",
        " *",
        " *   palette.json  sha256 %s" % hashlib.sha256(
            open(pal_path, "rb").read()).hexdigest(),
        " *   font.bin      sha256 %s" % hashlib.sha256(font).hexdigest(),
        " */",
        "",
        '#include "moy.h"',
        "",
        "const uint8_t moy_palette_default[MOY_PALETTE * 3] = {",
    ]
    for i in range(0, len(rgb), 12):
        lines.append("    " + " ".join("%3d," % v for v in rgb[i:i + 12]))
    lines.append("};")
    lines.append("")
    lines.append("const uint8_t moy_font_data[96 * 8] = {")
    for i in range(0, len(font), 16):
        lines.append("    " + " ".join("0x%02x," % b for b in font[i:i + 16]))
    lines.append("};")
    lines.append("")

    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d palette entries, %d font bytes)"
          % (out, len(palette), len(font)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
